## Numpy

Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.In this session,we will cover the baucs of NumPy,docusing on arrays and vectorized operations.


In [1]:
!pip install numpy

In [3]:
import numpy as np

## create array using numpy
##create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)    ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 1D array
arr2=np.array([[1,2,3,4,5]])   ##list within a list
arr2.shape

(1, 5)

In [10]:
## 2D array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [13]:
np.arange(0,10,2).reshape(5,1)   ## Diaplay elements between 0-10 and gap in between them is of 2

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))  ## three rows and 4 columns and each element is 1 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Attributes of numpy
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output:(2,3)
print("Number of dimensions:", arr.ndim) # Output:2
print("Size(number of elements):", arr.size) #Output:6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size(in bytes):", arr.itemsize) # Output:8 (may vary based on platform )

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
Item size(in bytes): 8


In [19]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,5])

### ELement wise addition
print("Addition:",arr1 + arr2)

### ELement wise substraction
print("Substraction:",arr1 - arr2)

### ELement wise multiplication
print("Multiplication:",arr1 * arr2)

### ELement wise division
print("Division:",arr1/arr2)




Addition: [ 7  9 11 13 10]
Substraction: [-5 -5 -5 -5  0]
Multiplication: [ 6 14 24 36 25]
Division: [0.16666667 0.28571429 0.375      0.44444444 1.        ]


In [23]:
## Universal Fucntion 
arr=np.array([1,2,3,4,5])
## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [45]:
## array slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
print(arr[0][0])
print(arr[1:])

1
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [47]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [48]:
print(arr[0:2,1:])

[[2 3 4]
 [6 7 8]]


In [60]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [64]:
# Modify array elements
arr[0,0] = 40
print(arr)

[[ 40   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [65]:
arr[1:] = 100
print(arr)

[[ 40   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [66]:
## Statistical concepts--Normalisation
## to have a mean of 0 and standard deviation 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)


# Normalize the data 
Normalized_data = (data-mean)/std_dev
print("Normalized data:", Normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [67]:
data = np.array([1,2,3,4,5,6,7,8,9])

# Mean
mean = np.mean(data)
print("Mean",mean)

# Median
median = np.median(data)
print("Median",median)

#Standard Deviation
std_dev = np.std(data)
print("Standard Deviation",std_dev)

# Variance
variance = np.var(data)
print("Variance", variance)

Mean 5.0
Median 5.0
Standard Deviation 2.581988897471611
Variance 6.666666666666667


In [73]:
#Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5       ## Gives true/false value 
data[data>5] ## gives the lements greater than 5 
data[(data>5) & (data<8)] 

array([6, 7])